
ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS category text NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS brand text NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS buy_rate numeric NOT NULL DEFAULT 0;
